version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/bin"
      - "/packages/cli"
      - "/packages/core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      npm-deps:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      pip-deps:
        patterns: ["*"]
  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      cargo-deps:
        patterns: ["*"]
